### ISSUE TITLE
CPH stuck on "Loading"

### ISSUE THREAD

**Issue by boasbakker** [agrawal-d/cph#466] opened 2024-07-23 17:55 UTC
![afbeelding](https://github.com/user-attachments/assets/58b0dde3-e04b-4946-94d2-6bc2d9121efc)

**Extension Version:** v2024.7.1721655847

Visual Studio Code information:
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-44-generic snap

Ubuntu 22.04 LTS

I tried:
 - Restarting VScode
 - Different folder
 - Reinstalling extension

**Comment by opticSquid** [comment] 2024-07-24 03:10
Yes it also happens for me. I found another nuanse when I change the extension in output window the main window comes but no problem is created as shown in this recording:

https://github.com/user-attachments/assets/6f01af3e-e3e5-4e97-b077-eb4ce4559deb

CPH version: v2024.7.1721655847
OS:  Ubuntu 24.04 LTS
VS Code Version: 1.91

**Comment by opticSquid** [comment] 2024-07-24 03:18
This is the mp4 version of my previous screen recording in case if you have problems opening webm files:

https://github.com/user-attachments/assets/6f01af3e-e3e5-4e97-b077-eb4ce4559deb

**Comment by Ease-at-Bhumesh** [comment] 2024-07-24 06:24
Use this extension CPH (Jamal's Edition).
It is working for me.

**Comment by pratyush2331** [comment] 2024-07-24 15:39
> ![afbeelding](https://private-user-images.githubusercontent.com/59883944/351437326-58b0dde3-e04b-4946-94d2-6bc2d9121efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzU2NTYsIm5iZiI6MTcyMTgzNTM1NiwicGF0aCI6Ii81OTg4Mzk0NC8zNTE0MzczMjYtNThiMGRkZTMtZTA0Yi00OTQ2LTk0ZDItNmJjMmQ5MTIxZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE1MzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNGRmNjY1MzE4NzU1NzNjN2QyY2UwMGJiYzY1MTBhMzRkNmM3NDFiZmYwZGM1MzA0M2ViNmExYTZkNmIyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9METV0x6MoDgCuWjuoqY-AgbSf0QA2l-fBv_la61hs)
> 
> **Extension Version:** v2024.7.1721655847
> 
> Visual Studio Code information: Version: 1.91.1 Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729 Date: 2024-07-09T22:08:12.169Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Linux x64 6.5.0-44-generic snap
> 
> Ubuntu 22.04 LTS
> 
> I tried:
> 
> * Restarting VScode
> * Different folder
> * Reinstalling extension

same issue

**Comment by imeanup** [comment] 2024-07-24 17:47
Go to the extension and select another version from a month back until the issue is identified.

**Comment by ShivamS136** [comment] 2024-07-25 09:19
I am also facing the same issue. Please fix this.

**Comment by AprLsity** [comment] 2024-07-25 15:29
same issue
v2024.7.1721655847

**Comment by tr1ten** [comment] 2024-07-25 16:58
Same issue

**Comment by agrawal-d** [comment] 2024-07-25 18:59
I'll look into this.

**Comment by suraj1771singh** [comment] 2024-07-26 20:17
same problemmm

**Comment by agrawal-d** [comment] 2024-07-27 09:40
I can't repro this. Can folks in this thread share the console logs with me.
1. Open a problem in VS Code.
2. Go to the CPH tab.
3. Press Ctrl+Shift+P
4. Type `workbench.action.webview.openDeveloperTools` and hit enter
5. Then follow the steps in the video, open the "Console" tab, press "Ctrl+A" to select logs then "Ctrl+C" to copy.
6. Copy the logs to a file and please share the logs here.

CC @boasbakker @opticSquid and others.

https://github.com/user-attachments/assets/b6d8d514-61ab-489d-9770-686379368a4f

**Comment by jugshaurya** [comment] 2024-07-27 13:40
@agrawal-d 
```js
frontend.module.js:2 ReferenceError: vscodeApi is not defined
    at frontend.module.js:2:144009
    at Object.Uo [as useState] (frontend.module.js:2:65734)
    at t.useState (frontend.module.js:2:138842)
    at f (frontend.module.js:2:143994)
    at xo (frontend.module.js:2:62817)
    at xi (frontend.module.js:2:119649)
    at ws (frontend.module.js:2:108801)
    at ys (frontend.module.js:2:108729)
    at vs (frontend.module.js:2:108592)
    at os (frontend.module.js:2:105399)
du @ frontend.module.js:2
n.callback @ frontend.module.js:2
Ua @ frontend.module.js:2
ki @ frontend.module.js:2
wi @ frontend.module.js:2
bi @ frontend.module.js:2
(anonymous) @ frontend.module.js:2
Ss @ frontend.module.js:2
as @ frontend.module.js:2
S @ frontend.module.js:2
T @ frontend.module.js:2
frontend.module.js:2 Uncaught ReferenceError: vscodeApi is not defined
    at frontend.module.js:2:144009
    at Object.Uo [as useState] (frontend.module.js:2:65734)
    at t.useState (frontend.module.js:2:138842)
    at f (frontend.module.js:2:143994)
    at xo (frontend.module.js:2:62817)
    at xi (frontend.module.js:2:119649)
    at ws (frontend.module.js:2:108801)
    at ys (frontend.module.js:2:108729)
    at vs (frontend.module.js:2:108592)
    at os (frontend.module.js:2:105399)
    ```

**Comment by Readiz** [comment] 2024-07-28 01:12
same for me...

**Comment by opticSquid** [comment] 2024-07-28 08:28
Now the issue is resolved for me. When I checked today morning. Other folks also can comment. If it works for everyone we can close this issue

**Comment by ShivamS136** [comment] 2024-07-28 08:59
I switched to old version (1 month ago) and it started working. After seeing previous update in this thread, I tried to auto update again but the latest version was the same 5 days ago version. I reloaded the extensions and surprisingly it extension was working. But when I quitted VS code and restarted it then again the extension is not working.

**Comment by ShivamS136** [comment] 2024-07-28 09:04
Error for me in the console is:

```
VM10:5 Uncaught SyntaxError: Unexpected identifier 'also'
```

And the opened file is below:

```

                        // Since the react script takes time to load, the problem is sent to the webview before it has even loaded.
                        // So, for the initial request, ask for it again.
                        window.vscodeApi = acquireVsCodeApi();
                        window.remoteMessage = Now also for Google Chrome: Submit directly to Codeforces using <a href="https://github.com/agrawal-d/cph-submit">CPH-Submit</a>!
                                                    ^^^ // Error is here
;
                        document.addEventListener(
                            'DOMContentLoaded',
                            (event) => {
                                vscodeApi.postMessage({
                                    command: 'get-initial-problem',
                                });
                                vscodeApi.postMessage({
                                    command: 'online-judge-env',
                                    value:false,
                                });
                                console.log("Requested initial problem");
                            },
                        );
```

I think value of `window.remoteMessage` should have been a string (enclosed in double quotes instead of plain text).

**Comment by T2hhbmEK** [comment] 2024-07-29 06:42
> VM10:5 Uncaught SyntaxError: Unexpected identifier 'also'

Same error msg here as @ShivamS136 mentioned above.

**Comment by agrawal-d** [comment] 2024-07-30 05:14
Should be fixed in the new version. Please update to the latest version.

**Closed as completed by agrawal-d** 2024-07-30 05:14 UTC
