### ISSUE TITLE
The result from CPH is different from terminal.

### ISSUE THREAD

**Issue by nguyenduyminhthong** [agrawal-d/cph#95] opened 2020-11-06 09:22 UTC
The result that I received from CPH extension is different from terminal. This is my screenshot, how can I fix it?
![image](https://user-images.githubusercontent.com/54903090/98348719-b0749b00-204b-11eb-8e37-5812d3d6de3a.png)

**Extension Version:** <4.4.6>
  
**VS Code Version:** <1.50.1>
  
**Chrome Version:** <83.0.4103.122>
  
**Operating System:** <Linux x64 5.8.0-7625-generic>

**Comment by agrawal-d** [comment] 2020-12-09 06:41
Perhaps it is due to different python interpreters? Try changing the python interpreter path from CPH settings within VS Code settings.

**Comment by Optider** [comment] 2020-12-23 13:41
The issue is resolved.
Kindly close this issue.
As the issue was not with the extension but a conflict of different python versions.

**Closed as completed** 2020-12-28 12:49 UTC
