### ISSUE TITLE
Bug : Input and Output is not getting parsed correctly

### ISSUE THREAD

**Issue by imshree03** [agrawal-d/cph#451] opened 2024-06-17 05:49 UTC
![Screenshot 2024-06-17 111033](https://github.com/agrawal-d/cph/assets/107460907/5ab532f3-cb00-4412-a555-b95cd416f6eb)

Input and Output is not getting parsed correctly not sure why? Please fix this.

**Extension Version:** v2024.6.1718565457

**Browser Version:** (Chrome) 126.0.6478.62

**Operating System:** Windows 11 Home Single Language Version 23H2

**Comment by imshree03** [comment] 2024-06-17 05:51
I have even updated chrome browser and everything but still this issue persists help @agrawal-d

**Comment by imeanup** [comment] 2024-06-17 14:20
Have you tried the basic troubleshooting steps to resolve the issue?

Tried installing Competitive Companion in a different browser and install CPH in a different profile inside VSCode?

Please try to debug as much as you can and share the result so that someone could help you. 

> Please also share complete information like the .cph file for the problem parsed data and problem statement. 

Kindly google (how to) if you are unable to find or location the hidden in VSCode .cph folder in VSCode.

**Comment by imshree03** [comment] 2024-06-18 05:43
@imeanup yeah thanks it works on edge but somehow it is not working in chrome. Apart from this this issue was occuring irrespective for lot of problem statements on cf. should i share the .cph file as well lmk?

**Comment by imeanup** [comment] 2024-06-18 15:24
Probably the best approach would be to create a new user in Chrome or enable CPH in Private Window, and push the information towards VSCode. I would not suggest to reset Chrome as it may result in unknown consequences. 

However, the issue is not related to CPH but rather on the browser end. Moreover, you may disabled all extensions installed in Chrome and reinstall  Competitive Companion and try (this is a basic troubleshooting which I would suggest, rest at your own risk. Take necessary backup before doing/performing any changes/steps as it may results in permanent loss of data).

Thus, you may close this issue @agrawal-d . 

Thank you.

**Closed as completed** 2024-06-18 17:34 UTC
