### ISSUE TITLE
I add a New Testcase, and it delete all the previous testcase

### ISSUE THREAD

**Issue by SPyofgame200** [agrawal-d/cph#10] opened 2020-02-11 03:41 UTC

**Comment by agrawal-d** [comment] 2020-02-11 03:52
Thanks for the bug report!

This should not be happening. Can you give me some more details so that I can reproduce this bug? Specifically:

1. Are the previous testcases created manually, or downloaded using competitive companion?
1. If you are using competitive companion, can you share the problem URL with me?
1. Which version of the extension are you using? You can find out by searching for it in Extensions frm the Activity Bar:
![image](https://user-images.githubusercontent.com/7714968/74209990-fca6d080-4caf-11ea-9b56-95ad500f3c71.png)

**Comment by knayan111** [comment] 2020-02-18 10:24
It happens when more than one test cases are added manually without pressing "Save and run" button after adding every test case. Previous manually added test cases are not saved when "New" or "New testcase" button is pressed.

**Comment by agrawal-d** [comment] 2020-02-18 10:54
Yes, it's true. Testcases are not saved Unless you press "Save and Run" or run a single testcase. Its not a bug per se, rather the way the extension works. I will consider auto save feature in the future. Closing this issue now. If you have any further questions, please comment here, and I will open this issue again, if needed.

Thanks for the report!

**Closed as completed by agrawal-d** 2020-02-18 10:55 UTC
