### ISSUE TITLE
why if there're warnings, the program can't work.

### ISSUE THREAD

**Issue by zhk1211** [agrawal-d/cph#274] opened 2022-07-13 06:05 UTC
when there're warnings with my code, the program can't work.

**Comment by zhk1211** [comment] 2022-07-13 07:17
Is there any one help me?

**Comment by zhk1211** [comment] 2022-07-13 07:18
@agrawal-d @mr2rm @Haizs @mitkonikov

**Comment by zhk1211** [comment] 2022-07-13 07:19
<img width="1002" alt="iShot_2022-07-13_15 19 15" src="https://user-images.githubusercontent.com/60701418/178674382-65062b11-8d50-4683-a6b5-1eebb1ad2f36.png">

**Comment by zhk1211** [comment] 2022-07-24 07:16
@agrawal-d how to deal with it?

**Comment by zhk1211** [comment] 2022-08-04 13:09
@adarsh-dhakad

**Comment by zhk1211** [comment] 2022-08-06 09:02
@agrawal-d @mr2rm

**Comment by adamant-pwn** [comment] 2022-12-20 00:06
This is a duplicate of https://github.com/agrawal-d/cph/issues/214. But I think it is very important to fix it anyway because it's possible to distinguish warnings and errors (warnings don't prevent the generation of the exe file).

**Closed as completed** 2023-11-26 13:46 UTC
